# Generated by Django 4.2.8 on 2025-11-24 07:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bustk', '0004_useremail'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seats', models.TextField(help_text='Danh sách ghế, ví dụ: A01,B02,B03')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12)),
                ('ticket_code', models.CharField(max_length=32, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Đang chờ'), ('paid', 'Đã thanh toán'), ('expired', 'Hết hạn')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bustk.trip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
