# Generated by Django 4.2.8 on 2025-11-24 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bustk', '0005_paymentorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentorder',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='seats',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Đang chờ thanh toán'), ('paid', 'Đã thanh toán'), ('expired', 'Hết hạn')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='ticket_code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bustk.trip'),
        ),
    ]
