# Generated by Django 4.2.8 on 2025-11-25 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bustk', '0006_paymentorder_paid_at_alter_paymentorder_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='payment_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='bustk.paymentorder'),
        ),
    ]
