# Generated by Django 4.2.8 on 2025-11-25 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bustk', '0009_alter_ticket_trip'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentorder',
            name='departure_str',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='from_location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='price_each',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='to_location',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
