# Generated by Django 4.2.8 on 2025-11-25 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bustk', '0010_paymentorder_departure_str_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentorder',
            name='departure_str',
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='depart_date',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='depart_time',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
