# Generated by Django 4.2.8 on 2025-11-26 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bustk', '0011_remove_paymentorder_departure_str_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='messages/'),
        ),
    ]
