# Generated by Django 4.2.8 on 2025-11-27 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bustk', '0012_message_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='completed_notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='reminder_30m_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='started_notified',
            field=models.BooleanField(default=False),
        ),
    ]
