# Generated by Django 4.2.8 on 2025-11-27 05:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bustk', '0013_ticket_completed_notified_ticket_reminder_30m_sent_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='message',
            new_name='body',
        ),
        migrations.AddField(
            model_name='notification',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='bustk.ticket'),
        ),
        migrations.AddField(
            model_name='notification',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='bustk.trip'),
        ),
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('BOOKING_SUCCESS', 'Đặt vé thành công'), ('CANCEL_SUCCESS', 'Hủy vé thành công'), ('UPCOMING_REMINDER', 'Nhắc chuyến sắp khởi hành'), ('DEPARTURE', 'Chuyến xe đang khởi hành'), ('COMPLETED', 'Chuyến xe đã hoàn thành'), ('SYSTEM', 'Hệ thống')], default='SYSTEM', max_length=30),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
