# Generated by Django 4.2.8 on 2025-11-27 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bustk', '0014_rename_message_notification_body_notification_ticket_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={},
        ),
        migrations.AlterField(
            model_name='notification',
            name='body',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='bustk.ticket'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='notification',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='bustk.trip'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('booking_success', 'Đặt vé thành công'), ('cancel_success', 'Hủy vé thành công'), ('trip_reminder', 'Chuyến xe sắp khởi hành'), ('trip_start', 'Chuyến xe đang khởi hành'), ('trip_completed', 'Chuyến xe đã hoàn thành'), ('other', 'Thông báo khác')], default='other', max_length=50),
        ),
    ]
